// Generated by scripts/voice/calibrate.py: how the voice comparison reads the style model's
// cosine similarity (p = sigmoid(a * similarity + b), the odds the same person wrote both).
window.SlopgaugeVoiceCal = {"whole": [25.2678, -19.5761], "accuracy": 7, "window": [22.0896, -16.3195], "sameAbove": 0.7, "diffBelow": 0.1, "offBelow": 0.1, "rates": {"ownDiff": 0.02, "aiDiff": 0.403, "ownSame": 0.63, "aiSame": 0.013, "ownOff": 0.018, "aiOff": 0.205}};
