# Writes js/voice-cal.js: turns the style model's cosine similarity into the odds that the same person
# wrote both texts, for whole texts and ~120-word parts. Input: similarities measured on held-out
# Reddit writers (webis-tldr-17, CC BY 4.0), between a writer's known posts and (a) another post of
# theirs, (b) a post by someone else in the same subreddit, (c) an AI-written Reddit post:
#   python scripts/voice/calibrate.py luar_calib.json
import json, os, sys
import numpy as np
from sklearn.linear_model import LogisticRegression
d = json.load(open(sys.argv[1]))
out = {}
for key, (pos, neg, ai) in {'whole': ('pos', 'neg', 'ai'), 'window': ('pos_w', 'neg_w', 'ai_w')}.items():
    p, n = np.array(d[pos]), np.array(d[neg] + d[ai])
    # Same writer vs not, with the two kinds of "not" weighted equally and the classes balanced.
    w = np.r_[np.ones(len(p)) / len(p), np.ones(len(n)) / len(n)]
    x = np.r_[p, n].reshape(-1, 1); y = np.r_[np.ones(len(p)), np.zeros(len(n))]
    lr = LogisticRegression(C=100).fit(x, y, sample_weight=w * len(y))
    a, b = float(lr.coef_[0][0]), float(lr.intercept_[0])
    prob = lambda s: 1 / (1 + np.exp(-(a * np.asarray(s) + b)))
    out[key] = [round(a, 4), round(b, 4)]
    acc = (np.mean(prob(p) >= 0.5) + np.mean(prob(np.array(d[neg])) < 0.5)) / 2
    print(f'{key}: p = sigmoid({a:.2f}*sim + {b:.2f}); balanced accuracy vs other people {acc:.2f}')
    for lo, hi in ((0.3, 0.7), (0.25, 0.75)):
        print(f'  "doesn\'t sound like them" below {lo}: their own text {np.mean(prob(p) < lo):.1%}, others {np.mean(prob(np.array(d[neg])) < lo):.1%}, AI {np.mean(prob(np.array(d[ai])) < lo):.1%}'
              f' | "sounds like them" above {hi}: own {np.mean(prob(p) >= hi):.1%}, others {np.mean(prob(np.array(d[neg])) >= hi):.1%}, AI {np.mean(prob(np.array(d[ai])) >= hi):.1%}')
    if key == 'whole':
        out['accuracy'] = int(round(acc * 10))
# "Doesn't sound like them" is close to an accusation, so it fires only where a writer's own text
# rarely lands: below 0.1 (whole: own 2%, AI 40%, someone else 20%; parts: own 1.8%, AI 20%).
out.update({'sameAbove': 0.7, 'diffBelow': 0.1, 'offBelow': 0.1})
pw, aw = np.array(d['pos']), np.array(d['ai'])
prob = lambda s, k: 1 / (1 + np.exp(-(out[k][0] * np.asarray(s) + out[k][1])))
out['rates'] = {'ownDiff': round(float(np.mean(prob(pw, 'whole') < 0.1)), 3), 'aiDiff': round(float(np.mean(prob(aw, 'whole') < 0.1)), 3),
                'ownSame': round(float(np.mean(prob(pw, 'whole') >= 0.7)), 3), 'aiSame': round(float(np.mean(prob(aw, 'whole') >= 0.7)), 3),
                'ownOff': round(float(np.mean(prob(d['pos_w'], 'window') < 0.1)), 3), 'aiOff': round(float(np.mean(prob(d['ai_w'], 'window') < 0.1)), 3)}
root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
with open(os.path.join(root, 'js', 'voice-cal.js'), 'w') as f:
    f.write('// Generated by scripts/voice/calibrate.py: how the voice comparison reads the style model\'s\n')
    f.write('// cosine similarity (p = sigmoid(a * similarity + b), the odds the same person wrote both).\n')
    f.write('window.SlopgaugeVoiceCal = ' + json.dumps(out) + ';\n')
print(out)
