// Calibrates the essay checker per kind of text and writes js/odds.js.
//   node scripts/odds/calibrate.js held-out.json school.json
// held-out.json: the checker's scores on held-out texts from the training corpora, a list of
//   { dom, y, doc, sents: [[logit, words]] } (the extension repo's scripts/model/ data).
// school.json: { human: [...], ai: [...] } with the same fields, for school essays by students in
//   grades 6-12 (PERSUADE 2.0, CC BY-NC-SA 4.0, used only to test and set thresholds here) and AI
//   essays written for the same prompts (DAIGT, Apache-2.0).
// For each kind, thresholds are set on its human texts: "Likely AI-written" for at most 1 in 100,
// "Possibly" for at most 5 in 100; a sentence is marked for at most 2 in 100 human words ("maybe"
// 5 in 100). Kinds with few human texts borrow the strictest thresholds.
const fs = require('fs');
const path = require('path');
const [heldPath, schoolPath] = process.argv.slice(2);
const held = JSON.parse(fs.readFileSync(heldPath, 'utf8'));
const school = JSON.parse(fs.readFileSync(schoolPath, 'utf8'));
const KINDS = {
  school: ['School essays (grades 6 to 12)', null],
  essay: ['College essays', ['dactyl/student_essays', 'gb/essay']],
  learner: ['Essays by English learners', ['gb/non-native']],
  story: ['Stories', ['dactyl/RedditWritingPrompts', 'gb/wp']],
  news: ['News and articles', ['dactyl/news', 'gb/reuter', 'hndc/news', 'maga/CC News', 'maga/NPR News', 'evo/xsum']],
  post: ['Online posts and how-tos', ['m4/reddit', 'maga/Reddit', 'm4/wikihow']],
};
const rows = (kind, y) =>
  kind === 'school'
    ? (y ? school.ai : school.human)
    : kind === 'all'
      ? [...held.filter((r) => r.y === y), ...(y ? school.ai : school.human)]
      : held.filter((r) => r.y === y && KINDS[kind][1].includes(r.dom));
const quantile = (xs, p) => {
  const s = [...xs].sort((a, b) => a - b);
  return s[Math.min(s.length - 1, Math.max(0, Math.ceil(p * s.length) - 1))];
};
// The sentence threshold at which `share` of human words are marked.
function wordQuantile(rs, share) {
  const pairs = rs.flatMap((r) => r.sents.filter((s) => s[0] !== null)).sort((a, b) => b[0] - a[0]);
  const total = pairs.reduce((n, s) => n + s[1], 0);
  let n = 0;
  for (const [logit, w] of pairs) {
    n += w;
    if (n / total > share) return logit;
  }
  return pairs.length ? pairs[pairs.length - 1][0] : 0;
}
const r3 = (x) => Math.round(x * 1000) / 1000;
const out = {};
for (const kind of [...Object.keys(KINDS), 'all']) {
  const H = rows(kind, 0).filter((r) => r.doc !== null);
  const A = rows(kind, 1).filter((r) => r.doc !== null);
  const cal = {
    docAI: quantile(H.map((r) => r.doc), 0.99),
    docMixed: quantile(H.map((r) => r.doc), 0.95),
    sentenceAI: wordQuantile(H, 0.02),
    sentenceMaybe: wordQuantile(H, 0.05),
    shareMixed: 0.3,
  };
  out[kind] = { label: kind === 'all' ? 'Something else' : KINDS[kind][0], n: H.length, cal };
  const thin = (xs) => {
    const s = xs.sort((a, b) => a - b);
    const step = Math.max(1, Math.floor(s.length / 400));
    return s.filter((_, i) => i % step === 0).map(r3);
  };
  out[kind].human = { n: H.length, q: thin(H.map((r) => r.doc)) };
  if (A.length) out[kind].ai = { n: A.length, q: thin(A.map((r) => r.doc)) };
}
// Kinds with under 200 human texts can't place a 1-in-100 threshold: use the strictest one.
const strict = (k) => Math.max(...Object.values(out).filter((v) => v.n >= 200).map((v) => v.cal[k]));
for (const v of Object.values(out)) if (v.n < 200) for (const k of ['docAI', 'docMixed', 'sentenceAI', 'sentenceMaybe']) v.cal[k] = strict(k);
for (const v of Object.values(out)) for (const k of Object.keys(v.cal)) v.cal[k] = r3(v.cal[k]);
// Report what these thresholds do.
for (const [kind, v] of Object.entries(out)) {
  const H = rows(kind, 0).filter((r) => r.doc !== null);
  const A = rows(kind, 1).filter((r) => r.doc !== null);
  const rate = (rs) => (rs.length ? ((100 * rs.filter((r) => r.doc >= v.cal.docAI).length) / rs.length).toFixed(1) : '-');
  console.log(`${kind.padEnd(8)} n ${String(H.length).padStart(5)}  Likely AI >= ${v.cal.docAI}: people ${rate(H)}%, AI ${rate(A)}%  | sentence ${v.cal.sentenceAI}/${v.cal.sentenceMaybe}`);
}
const root = path.resolve(__dirname, '..', '..');
fs.writeFileSync(
  path.join(root, 'js', 'odds.js'),
  `// Generated by scripts/odds/calibrate.js: per kind of text, the checker's thresholds and its
// whole-text scores on held-out texts by people and by AI (sorted, thinned to ~400 values each).
(function (root) {
  const T = ${JSON.stringify(out)};
  // Share of a sorted list at or above x.
  const above = (q, x) => {
    let lo = 0, hi = q.length;
    while (lo < hi) { const m = (lo + hi) >> 1; if (q[m] < x) lo = m + 1; else hi = m; }
    return (q.length - lo) / q.length;
  };
  /** odds(kind, docLogit) -> { label, human: {share, n}, ai: {share, n} | null } */
  function odds(kind, x) {
    const g = T[kind] || T.all;
    const one = (s) => (s ? { share: above(s.q, x), n: s.n } : null);
    return { label: g.label, human: one(g.human), ai: one(g.ai) };
  }
  const calibration = (kind) => (T[kind] || T.all).cal;
  const kinds = Object.entries(T).map(([k, v]) => [k, v.label]);
  const api = { odds, calibration, kinds };
  if (typeof module !== 'undefined' && module.exports) module.exports = api;
  else root.SlopgaugeOdds = api;
})(typeof globalThis !== 'undefined' ? globalThis : this);
`
);
console.log('wrote js/odds.js');
